export const bestItems = [
  {
    id: 1,
    rank: 1,
    brand: "헬로우슬립",
    title: "[최대20%쿠폰+사은품] 극세사출시! 카스테라 워싱 옥수수솜 사계절/한파용 차렵이불세트",
    discount: 39,
    price: 34900,
    rating: 4.8,
    reviews: 69455,
    image: "/images/best01.avif",
    thumbnails: ["/images/best01.avif"],
    badge: "특가",
    freeShipping: true
  },
  {
    id: 2,
    rank: 2,
    brand: "아일룸",
    title: "[최대 15% 쿠폰] 오늘 단 하루! 비침없는 도톰 레이스/쉬폰커튼(나비주름/핀형/봉집)",
    discount: 28,
    price: 16800,
    rating: 4.8,
    reviews: 48948,
    image: "/images/best02.avif",
    thumbnails: ["/images/best02.avif"],
    badge: "특가",
    freeShipping: true
  },
  {
    id: 3,
    rank: 3,
    brand: "수면명도",
    title: "허리 디스크 환자가 만든 매트리스 S/SS/Q/K/LK 미디엄하드 S",
    discount: 62,
    price: 299000,
    rating: 4.9,
    reviews: 11192,
    image: "/images/best03.avif",
    thumbnails: ["/images/best03.avif"],
    badge: "특가",
    freeShipping: true
  },
  {
    id: 4,
    rank: 4,
    brand: "모노하우스",
    title: "모던 화이트 5단 서랍장",
    discount: 30,
    price: 59000,
    rating: 4.7,
    reviews: 8201,
    image: "/images/best04.avif",
    thumbnails: ["/images/best04.avif"],
    badge: "특가",
    freeShipping: true
  },
  {
    id: 5,
    rank: 5,
    brand: "심플리홈",
    title: "심플 원목 사다리 선반 4단",
    discount: 27,
    price: 29900,
    rating: 4.8,
    reviews: 19532,
    image: "/images/best05.avif",
    thumbnails: ["/images/best05.avif"],
    badge: "특가",
    freeShipping: true
  },
  {
    id: 6,
    rank: 6,
    brand: "홈인테리어",
    title: "포근한 극세사 차렵이불 세트",
    discount: 33,
    price: 45900,
    rating: 4.7,
    reviews: 14220,
    image: "/images/best06.avif",
    thumbnails: ["/images/best06.avif"],
    badge: "특가",
    freeShipping: true
  },
  {
    id: 7,
    rank: 7,
    brand: "라이프데코",
    title: "인기 원목 4인용 식탁 세트",
    discount: 25,
    price: 199000,
    rating: 4.8,
    reviews: 7340,
    image: "/images/best07.avif",
    thumbnails: ["/images/best07.avif"],
    badge: "특가",
    freeShipping: true
  },
  {
    id: 8,
    rank: 8,
    brand: "코지하우스",
    title: "폭신한 구름 극세사 토퍼",
    discount: 40,
    price: 29900,
    rating: 4.9,
    reviews: 20100,
    image: "/images/best08.avif",
    thumbnails: ["/images/best08.avif"],
    badge: "특가",
    freeShipping: true
  }
];
