export const deals = [
  {
    id: 1,
    brand: "빅토리아",
    title: "빅토리아 탄산수 500ml X 40",
    subTitle: "시원한 탄산, 대용량으로 합리적인 가격",
    discount: 29,
    price: 16900,
    rating: 4.8,
    reviewCount: 69455,
    free: true,
    image: "/images/deal01.avif"
  },
  {
    id: 2,
    brand: "허그미홈즈",
    title: "따뜻한 겨울 이불 패키지",
    subTitle: "포근한 극세사 이불로 겨울 준비 끝!",
    discount: 39,
    price: 34900,
    rating: 4.7,
    reviewCount: 38210,
    free: true,
    image: "/images/deal02.avif"
  },
  {
    id: 3,
    brand: "삼성전자",
    title: "삼성전자 건조기 인기패키지",
    subTitle: "한 번에 바삭하게! 대용량 건조기",
    discount: 41,
    price: 880000,
    rating: 4.9,
    reviewCount: 11290,
    free: false,
    image: "/images/deal03.avif"
  },
  {
    id: 4,
    brand: "모노하우스",
    title: "프리미엄 소파 3인용",
    subTitle: "넓고 편안한 거실 공간 만들기",
    discount: 32,
    price: 299000,
    rating: 4.8,
    reviewCount: 12980,
    free: false,
    image: "/images/deal04.avif"
  },
  {
    id: 5,
    brand: "루미리빙",
    title: "LED 무드등 스탠드",
    subTitle: "따뜻한 분위기를 위한 라이트",
    discount: 54,
    price: 15900,
    rating: 4.6,
    reviewCount: 8412,
    free: true,
    image: "/images/deal05.avif"
  },
  {
    id: 6,
    brand: "파워클린",
    title: "대형 청소기 패키지",
    subTitle: "강력한 흡입력으로 먼지 완전 제거!",
    discount: 18,
    price: 99000,
    rating: 4.7,
    reviewCount: 7150,
    free: false,
    image: "/images/deal06.avif"
  },
  {
    id: 7,
    brand: "우드홈",
    title: "원목 테이블 패키지",
    subTitle: "자연스러운 원목 감성 그대로",
    discount: 37,
    price: 99000,
    rating: 4.8,
    reviewCount: 5203,
    free: false,
    image: "/images/deal07.avif"
  },
  {
    id: 8,
    brand: "라탄하우스",
    title: "라탄 수납장",
    subTitle: "따뜻한 감성의 실용적인 수납장",
    discount: 22,
    price: 39000,
    rating: 4.6,
    reviewCount: 6893,
    free: true,
    image: "/images/deal08.avif"
  },
  {
    id: 9,
    brand: "코지러그",
    title: "러그 200x230",
    subTitle: "부드럽고 따뜻한 러그",
    discount: 35,
    price: 29900,
    rating: 4.7,
    reviewCount: 19220,
    free: true,
    image: "/images/deal09.avif"
  },
  {
    id: 10,
    brand: "아로마홈",
    title: "디퓨저 & 캔들 세트",
    subTitle: "집안에 채워지는 향기로운 무드",
    discount: 42,
    price: 19900,
    rating: 4.9,
    reviewCount: 15881,
    free: true,
    image: "/images/deal10.avif"
  }
];
